#############################################################################
# Makefile for building: HW3
# Generated by qmake (2.01a) (Qt 4.8.4) on: Mon Feb 11 00:08:03 2013
# Project:  Terrain.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/local/Qt4.8/mkspecs/macx-g++ CONFIG+=release CONFIG+=x86_64 -o Makefile Terrain.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Qt4.8/mkspecs/macx-g++ -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/Library/Frameworks/QtOpenGL.framework/Versions/4/Headers -I/usr/include/QtOpenGL -I/usr/include -I. -I/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/System/Library/Frameworks/AGL.framework/Headers -I. -F/Library/Frameworks
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Library/Frameworks -L/Library/Frameworks -framework QtOpenGL -framework QtGui -framework QtCore -framework OpenGL -framework AGL 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = renderwidget.cpp \
		main.cpp \
		rw_input.cpp moc_renderwidget.cpp
OBJECTS       = renderwidget.o \
		main.o \
		rw_input.o \
		moc_renderwidget.o
DIST          = /usr/local/Qt4.8/mkspecs/common/unix.conf \
		/usr/local/Qt4.8/mkspecs/common/mac.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Qt4.8/mkspecs/common/g++-base.conf \
		/usr/local/Qt4.8/mkspecs/common/g++-macx.conf \
		/usr/local/Qt4.8/mkspecs/qconfig.pri \
		/usr/local/Qt4.8/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Qt4.8/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.8/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.8/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.8/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.8/mkspecs/features/release.prf \
		/usr/local/Qt4.8/mkspecs/features/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/x86_64.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.8/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.8/mkspecs/features/qt.prf \
		/usr/local/Qt4.8/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt4.8/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.8/mkspecs/features/moc.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.8/mkspecs/features/resources.prf \
		/usr/local/Qt4.8/mkspecs/features/uic.prf \
		/usr/local/Qt4.8/mkspecs/features/yacc.prf \
		/usr/local/Qt4.8/mkspecs/features/lex.prf \
		/usr/local/Qt4.8/mkspecs/features/include_source_dir.prf \
		Terrain.pro
QMAKE_TARGET  = HW3
DESTDIR       = 
TARGET        = HW3

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Terrain.pro  /usr/local/Qt4.8/mkspecs/macx-g++/qmake.conf /usr/local/Qt4.8/mkspecs/common/unix.conf \
		/usr/local/Qt4.8/mkspecs/common/mac.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Qt4.8/mkspecs/common/g++-base.conf \
		/usr/local/Qt4.8/mkspecs/common/g++-macx.conf \
		/usr/local/Qt4.8/mkspecs/qconfig.pri \
		/usr/local/Qt4.8/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Qt4.8/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.8/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.8/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.8/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.8/mkspecs/features/release.prf \
		/usr/local/Qt4.8/mkspecs/features/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/x86_64.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.8/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.8/mkspecs/features/qt.prf \
		/usr/local/Qt4.8/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt4.8/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.8/mkspecs/features/moc.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.8/mkspecs/features/resources.prf \
		/usr/local/Qt4.8/mkspecs/features/uic.prf \
		/usr/local/Qt4.8/mkspecs/features/yacc.prf \
		/usr/local/Qt4.8/mkspecs/features/lex.prf \
		/usr/local/Qt4.8/mkspecs/features/include_source_dir.prf \
		/Library/Frameworks/QtOpenGL.framework/QtOpenGL.prl \
		/Library/Frameworks/QtGui.framework/QtGui.prl \
		/Library/Frameworks/QtCore.framework/QtCore.prl
	$(QMAKE) -spec /usr/local/Qt4.8/mkspecs/macx-g++ CONFIG+=release CONFIG+=x86_64 -o Makefile Terrain.pro
/usr/local/Qt4.8/mkspecs/common/unix.conf:
/usr/local/Qt4.8/mkspecs/common/mac.conf:
/usr/local/Qt4.8/mkspecs/common/gcc-base.conf:
/usr/local/Qt4.8/mkspecs/common/gcc-base-macx.conf:
/usr/local/Qt4.8/mkspecs/common/g++-base.conf:
/usr/local/Qt4.8/mkspecs/common/g++-macx.conf:
/usr/local/Qt4.8/mkspecs/qconfig.pri:
/usr/local/Qt4.8/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Qt4.8/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.8/mkspecs/features/qt_config.prf:
/usr/local/Qt4.8/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.8/mkspecs/features/default_pre.prf:
/usr/local/Qt4.8/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt4.8/mkspecs/features/release.prf:
/usr/local/Qt4.8/mkspecs/features/default_post.prf:
/usr/local/Qt4.8/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.8/mkspecs/features/mac/x86_64.prf:
/usr/local/Qt4.8/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.8/mkspecs/features/warn_on.prf:
/usr/local/Qt4.8/mkspecs/features/qt.prf:
/usr/local/Qt4.8/mkspecs/features/unix/opengl.prf:
/usr/local/Qt4.8/mkspecs/features/unix/thread.prf:
/usr/local/Qt4.8/mkspecs/features/moc.prf:
/usr/local/Qt4.8/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.8/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.8/mkspecs/features/resources.prf:
/usr/local/Qt4.8/mkspecs/features/uic.prf:
/usr/local/Qt4.8/mkspecs/features/yacc.prf:
/usr/local/Qt4.8/mkspecs/features/lex.prf:
/usr/local/Qt4.8/mkspecs/features/include_source_dir.prf:
/Library/Frameworks/QtOpenGL.framework/QtOpenGL.prl:
/Library/Frameworks/QtGui.framework/QtGui.prl:
/Library/Frameworks/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt4.8/mkspecs/macx-g++ CONFIG+=release CONFIG+=x86_64 -o Makefile Terrain.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/HW31.0.0 || $(MKDIR) .tmp/HW31.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/HW31.0.0/ && $(COPY_FILE) --parents renderwidget.h .tmp/HW31.0.0/ && $(COPY_FILE) --parents renderwidget.cpp main.cpp rw_input.cpp .tmp/HW31.0.0/ && (cd `dirname .tmp/HW31.0.0` && $(TAR) HW31.0.0.tar HW31.0.0 && $(COMPRESS) HW31.0.0.tar) && $(MOVE) `dirname .tmp/HW31.0.0`/HW31.0.0.tar.gz . && $(DEL_FILE) -r .tmp/HW31.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_renderwidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_renderwidget.cpp
moc_renderwidget.cpp: glm/glm.hpp \
		glm/core/_fixes.hpp \
		glm/core/setup.hpp \
		glm/core/_detail.hpp \
		glm/core/_vectorize.hpp \
		glm/core/type.hpp \
		glm/core/type_half.hpp \
		glm/core/type_half.inl \
		glm/core/type_float.hpp \
		glm/core/type_int.hpp \
		glm/core/type_gentype.hpp \
		glm/core/type_size.hpp \
		glm/core/type_vec1.hpp \
		glm/core/type_vec.hpp \
		glm/core/_swizzle.hpp \
		glm/core/_swizzle_func.hpp \
		glm/core/type_vec1.inl \
		glm/core/type_vec2.hpp \
		glm/core/type_vec2.inl \
		glm/core/type_vec3.hpp \
		glm/core/type_vec3.inl \
		glm/core/type_vec4.hpp \
		glm/core/type_vec4.inl \
		glm/core/type_mat2x2.hpp \
		glm/core/type_mat.hpp \
		glm/core/type_mat2x2.inl \
		glm/core/type_mat2x3.hpp \
		glm/core/type_mat2x3.inl \
		glm/core/type_mat2x4.hpp \
		glm/core/type_mat2x4.inl \
		glm/core/type_mat3x2.hpp \
		glm/core/type_mat3x2.inl \
		glm/core/type_mat3x3.hpp \
		glm/core/type_mat3x3.inl \
		glm/core/type_mat3x4.hpp \
		glm/core/type_mat3x4.inl \
		glm/core/type_mat4x2.hpp \
		glm/core/type_mat4x2.inl \
		glm/core/type_mat4x3.hpp \
		glm/core/type_mat4x3.inl \
		glm/core/type_mat4x4.hpp \
		glm/core/type_mat4x4.inl \
		glm/core/func_trigonometric.hpp \
		glm/core/func_trigonometric.inl \
		glm/core/func_exponential.hpp \
		glm/core/func_exponential.inl \
		glm/core/func_common.hpp \
		glm/core/func_common.inl \
		glm/core/func_packing.hpp \
		glm/core/func_packing.inl \
		glm/core/func_geometric.hpp \
		glm/core/func_geometric.inl \
		glm/core/func_matrix.hpp \
		glm/core/func_matrix.inl \
		glm/core/func_vector_relational.hpp \
		glm/core/func_vector_relational.inl \
		glm/core/func_integer.hpp \
		glm/core/func_integer.inl \
		glm/core/func_noise.hpp \
		glm/core/func_noise.inl \
		glm/gtc/noise.hpp \
		glm/gtc/noise.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/half_float.hpp \
		glm/gtc/half_float.inl \
		glm/gtc/quaternion.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/quaternion.inl \
		glm/gtc/type_ptr.inl \
		renderwidget.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ renderwidget.h -o moc_renderwidget.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

renderwidget.o: renderwidget.cpp renderwidget.h \
		glm/glm.hpp \
		glm/core/_fixes.hpp \
		glm/core/setup.hpp \
		glm/core/_detail.hpp \
		glm/core/_vectorize.hpp \
		glm/core/type.hpp \
		glm/core/type_half.hpp \
		glm/core/type_half.inl \
		glm/core/type_float.hpp \
		glm/core/type_int.hpp \
		glm/core/type_gentype.hpp \
		glm/core/type_size.hpp \
		glm/core/type_vec1.hpp \
		glm/core/type_vec.hpp \
		glm/core/_swizzle.hpp \
		glm/core/_swizzle_func.hpp \
		glm/core/type_vec1.inl \
		glm/core/type_vec2.hpp \
		glm/core/type_vec2.inl \
		glm/core/type_vec3.hpp \
		glm/core/type_vec3.inl \
		glm/core/type_vec4.hpp \
		glm/core/type_vec4.inl \
		glm/core/type_mat2x2.hpp \
		glm/core/type_mat.hpp \
		glm/core/type_mat2x2.inl \
		glm/core/type_mat2x3.hpp \
		glm/core/type_mat2x3.inl \
		glm/core/type_mat2x4.hpp \
		glm/core/type_mat2x4.inl \
		glm/core/type_mat3x2.hpp \
		glm/core/type_mat3x2.inl \
		glm/core/type_mat3x3.hpp \
		glm/core/type_mat3x3.inl \
		glm/core/type_mat3x4.hpp \
		glm/core/type_mat3x4.inl \
		glm/core/type_mat4x2.hpp \
		glm/core/type_mat4x2.inl \
		glm/core/type_mat4x3.hpp \
		glm/core/type_mat4x3.inl \
		glm/core/type_mat4x4.hpp \
		glm/core/type_mat4x4.inl \
		glm/core/func_trigonometric.hpp \
		glm/core/func_trigonometric.inl \
		glm/core/func_exponential.hpp \
		glm/core/func_exponential.inl \
		glm/core/func_common.hpp \
		glm/core/func_common.inl \
		glm/core/func_packing.hpp \
		glm/core/func_packing.inl \
		glm/core/func_geometric.hpp \
		glm/core/func_geometric.inl \
		glm/core/func_matrix.hpp \
		glm/core/func_matrix.inl \
		glm/core/func_vector_relational.hpp \
		glm/core/func_vector_relational.inl \
		glm/core/func_integer.hpp \
		glm/core/func_integer.inl \
		glm/core/func_noise.hpp \
		glm/core/func_noise.inl \
		glm/gtc/noise.hpp \
		glm/gtc/noise.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/half_float.hpp \
		glm/gtc/half_float.inl \
		glm/gtc/quaternion.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/quaternion.inl \
		glm/gtc/type_ptr.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o renderwidget.o renderwidget.cpp

main.o: main.cpp renderwidget.h \
		glm/glm.hpp \
		glm/core/_fixes.hpp \
		glm/core/setup.hpp \
		glm/core/_detail.hpp \
		glm/core/_vectorize.hpp \
		glm/core/type.hpp \
		glm/core/type_half.hpp \
		glm/core/type_half.inl \
		glm/core/type_float.hpp \
		glm/core/type_int.hpp \
		glm/core/type_gentype.hpp \
		glm/core/type_size.hpp \
		glm/core/type_vec1.hpp \
		glm/core/type_vec.hpp \
		glm/core/_swizzle.hpp \
		glm/core/_swizzle_func.hpp \
		glm/core/type_vec1.inl \
		glm/core/type_vec2.hpp \
		glm/core/type_vec2.inl \
		glm/core/type_vec3.hpp \
		glm/core/type_vec3.inl \
		glm/core/type_vec4.hpp \
		glm/core/type_vec4.inl \
		glm/core/type_mat2x2.hpp \
		glm/core/type_mat.hpp \
		glm/core/type_mat2x2.inl \
		glm/core/type_mat2x3.hpp \
		glm/core/type_mat2x3.inl \
		glm/core/type_mat2x4.hpp \
		glm/core/type_mat2x4.inl \
		glm/core/type_mat3x2.hpp \
		glm/core/type_mat3x2.inl \
		glm/core/type_mat3x3.hpp \
		glm/core/type_mat3x3.inl \
		glm/core/type_mat3x4.hpp \
		glm/core/type_mat3x4.inl \
		glm/core/type_mat4x2.hpp \
		glm/core/type_mat4x2.inl \
		glm/core/type_mat4x3.hpp \
		glm/core/type_mat4x3.inl \
		glm/core/type_mat4x4.hpp \
		glm/core/type_mat4x4.inl \
		glm/core/func_trigonometric.hpp \
		glm/core/func_trigonometric.inl \
		glm/core/func_exponential.hpp \
		glm/core/func_exponential.inl \
		glm/core/func_common.hpp \
		glm/core/func_common.inl \
		glm/core/func_packing.hpp \
		glm/core/func_packing.inl \
		glm/core/func_geometric.hpp \
		glm/core/func_geometric.inl \
		glm/core/func_matrix.hpp \
		glm/core/func_matrix.inl \
		glm/core/func_vector_relational.hpp \
		glm/core/func_vector_relational.inl \
		glm/core/func_integer.hpp \
		glm/core/func_integer.inl \
		glm/core/func_noise.hpp \
		glm/core/func_noise.inl \
		glm/gtc/noise.hpp \
		glm/gtc/noise.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/half_float.hpp \
		glm/gtc/half_float.inl \
		glm/gtc/quaternion.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/quaternion.inl \
		glm/gtc/type_ptr.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

rw_input.o: rw_input.cpp renderwidget.h \
		glm/glm.hpp \
		glm/core/_fixes.hpp \
		glm/core/setup.hpp \
		glm/core/_detail.hpp \
		glm/core/_vectorize.hpp \
		glm/core/type.hpp \
		glm/core/type_half.hpp \
		glm/core/type_half.inl \
		glm/core/type_float.hpp \
		glm/core/type_int.hpp \
		glm/core/type_gentype.hpp \
		glm/core/type_size.hpp \
		glm/core/type_vec1.hpp \
		glm/core/type_vec.hpp \
		glm/core/_swizzle.hpp \
		glm/core/_swizzle_func.hpp \
		glm/core/type_vec1.inl \
		glm/core/type_vec2.hpp \
		glm/core/type_vec2.inl \
		glm/core/type_vec3.hpp \
		glm/core/type_vec3.inl \
		glm/core/type_vec4.hpp \
		glm/core/type_vec4.inl \
		glm/core/type_mat2x2.hpp \
		glm/core/type_mat.hpp \
		glm/core/type_mat2x2.inl \
		glm/core/type_mat2x3.hpp \
		glm/core/type_mat2x3.inl \
		glm/core/type_mat2x4.hpp \
		glm/core/type_mat2x4.inl \
		glm/core/type_mat3x2.hpp \
		glm/core/type_mat3x2.inl \
		glm/core/type_mat3x3.hpp \
		glm/core/type_mat3x3.inl \
		glm/core/type_mat3x4.hpp \
		glm/core/type_mat3x4.inl \
		glm/core/type_mat4x2.hpp \
		glm/core/type_mat4x2.inl \
		glm/core/type_mat4x3.hpp \
		glm/core/type_mat4x3.inl \
		glm/core/type_mat4x4.hpp \
		glm/core/type_mat4x4.inl \
		glm/core/func_trigonometric.hpp \
		glm/core/func_trigonometric.inl \
		glm/core/func_exponential.hpp \
		glm/core/func_exponential.inl \
		glm/core/func_common.hpp \
		glm/core/func_common.inl \
		glm/core/func_packing.hpp \
		glm/core/func_packing.inl \
		glm/core/func_geometric.hpp \
		glm/core/func_geometric.inl \
		glm/core/func_matrix.hpp \
		glm/core/func_matrix.inl \
		glm/core/func_vector_relational.hpp \
		glm/core/func_vector_relational.inl \
		glm/core/func_integer.hpp \
		glm/core/func_integer.inl \
		glm/core/func_noise.hpp \
		glm/core/func_noise.inl \
		glm/gtc/noise.hpp \
		glm/gtc/noise.inl \
		glm/gtc/type_ptr.hpp \
		glm/gtc/half_float.hpp \
		glm/gtc/half_float.inl \
		glm/gtc/quaternion.hpp \
		glm/gtc/constants.hpp \
		glm/gtc/constants.inl \
		glm/gtc/quaternion.inl \
		glm/gtc/type_ptr.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rw_input.o rw_input.cpp

moc_renderwidget.o: moc_renderwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_renderwidget.o moc_renderwidget.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

